name: semi_final_lab
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  google_fonts: ^3.0.1
  provider: ^6.0.4
  firebase_core: ^2.0.0
  firebase_auth: ^4.0.1
  cloud_firestore: ^4.0.1
  font_awesome_flutter: ^10.2.1
  google_sign_in: ^5.4.2
  http: ^0.13.5
  carousel_slider: ^4.1.1
  gradient_borders: ^0.2.0
  url_launcher: ^6.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.10.0

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 19

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: ChenileDeluxeTwo
      fonts:
        - asset: assets/fonts/Chenile Deluxe Two.ttf